---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: false

provisioner:
  name: salt_solo
  formula: sysdig
  pillars:
  state_top:
    base:
      '*':
        - sysdig

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.0

suites:
  - name: default
